const ACCOUNT_COLLECTION_REF = 'accounts';
const INSTITUTION_TOKEN_COLLECTION_REF = 'institutionTokens';

const USER_ID_REF = 'userId';
const CREATED_AT_REF = 'createdAt';

const ORDER_DESC = 'desc';

module.exports = {
    ACCOUNT_COLLECTION_REF : ACCOUNT_COLLECTION_REF,
    INSTITUTION_TOKEN_COLLECTION_REF : INSTITUTION_TOKEN_COLLECTION_REF,
    USER_ID_REF : USER_ID_REF,
    CREATED_AT_REF : CREATED_AT_REF,
    ORDER_DESC : ORDER_DESC
};